/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import entidades.Pasajero;
import accesodatos.PasajerosData;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author pablo
 */
public class GestionPasajeros extends javax.swing.JPanel {
    private Pasajero pasajActual = null;
    private PasajerosData pasajData = new PasajerosData();

    /**
     * Creates new form gestionPasajeros
     */
    public GestionPasajeros() {
        initComponents();
        nombreInvalido.setVisible(false);
        apellidoInvalido.setVisible(false);
        dniInvalido.setVisible(false);
        correoInvalido.setVisible(false);
        telefonoInvalido.setVisible(false);
          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAgregar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        nombreInvalido = new javax.swing.JLabel();
        apellidoInvalido = new javax.swing.JLabel();
        dniInvalido = new javax.swing.JLabel();
        correoInvalido = new javax.swing.JLabel();
        telefonoInvalido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtDNI = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jtTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAgregar.setBackground(new java.awt.Color(183, 199, 214));
        jbAgregar.setText("Agregar");
        jbAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 76, -1));

        jbEliminar.setBackground(new java.awt.Color(183, 199, 214));
        jbEliminar.setText("Eliminar");
        jbEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));
        jbEliminar.setEnabled(false);
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 76, -1));

        jbBuscar.setBackground(new java.awt.Color(183, 199, 214));
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.gray));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 76, -1));

        nombreInvalido.setForeground(new java.awt.Color(255, 0, 0));
        nombreInvalido.setText("Nombre inválido.");
        add(nombreInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 108, -1));

        apellidoInvalido.setForeground(new java.awt.Color(255, 0, 0));
        apellidoInvalido.setText("Apellido inválido.");
        add(apellidoInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 108, -1));

        dniInvalido.setForeground(new java.awt.Color(255, 0, 0));
        dniInvalido.setText("DNI inválido.");
        add(dniInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 84, -1));

        correoInvalido.setForeground(new java.awt.Color(255, 0, 0));
        correoInvalido.setText("Correo inválido");
        add(correoInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 98, -1));

        telefonoInvalido.setForeground(new java.awt.Color(255, 0, 0));
        telefonoInvalido.setText("Teléfono inválido");
        add(telefonoInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 108, -1));

        jLabel2.setFont(new java.awt.Font("Source Serif Pro Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Gestion de pasajeros");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNombreKeyReleased(evt);
            }
        });
        add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 190, -1));

        jtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtApellidoKeyReleased(evt);
            }
        });
        add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, -1));

        jtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDNIKeyReleased(evt);
            }
        });
        add(jtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 190, -1));

        jtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCorreoKeyReleased(evt);
            }
        });
        add(jtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 190, -1));

        jtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelKeyReleased(evt);
            }
        });
        add(jtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Telefono:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Apellido:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("DNI:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Correo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(jtDNI.getText());
        Pasajero pasajero = pasajData.buscarPasajeroDNI(dni);
        pasajData.eliminarPasajero(pasajero.getIdPasajero());
        jbEliminar.setEnabled(true);
        limpiarCampos();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        int dni = 0;
        int tel = 0;
        String nombre = null;
        String apellido = null;
        String correo = null;

        if(jtDNI.getText().isEmpty() || jtNombre.getText().isEmpty() || jtApellido.getText().isEmpty() || jtCorreo.getText().isEmpty() || jtTel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Hay campos sin completar");
        }else{
            //validar dni
            if(validarEntero(jtDNI.getText())){
                dni = Integer.parseInt(jtDNI.getText());
            }else{
                dniInvalido.setVisible(true);
            }

            //validar nombre
            if(validarTexto(jtNombre.getText())){
                nombre = jtNombre.getText();
            }else{
                nombreInvalido.setVisible(true);
            }

            //validar apellido
            if(validarTexto(jtApellido.getText())){
                apellido = jtApellido.getText();
            }else{
                apellidoInvalido.setVisible(true);
            }

            //validar telefono
            if(validarEntero(jtTel.getText())){
                tel = Integer.parseInt(jtTel.getText());
            }else{
                telefonoInvalido.setVisible(true);
            }
            correo = jtCorreo.getText();
            
            if (!dniInvalido.isVisible() && !nombreInvalido.isVisible() && !apellidoInvalido.isVisible() && !correoInvalido.isVisible()  && !telefonoInvalido.isVisible()) {
                if (pasajActual == null) {
                    pasajActual = new Pasajero(nombre,apellido,dni,correo,tel,true);
                    pasajData.guardarPasajero(pasajActual);
                }else{
                    pasajActual.setApellido(apellido);
                    pasajActual.setNombre(nombre);
                    pasajActual.setDni(dni);
                    pasajActual.setCorreo(correo);
                    pasajActual.setTel(tel);
                    pasajData.actualizarPasajero(pasajActual);
                }
                jbAgregar.setEnabled(true);

                limpiarCampos();
            }

        }

    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        int dni;

        if(validarEntero(jtDNI.getText())){
            dni = Integer.parseInt(jtDNI.getText());
            pasajActual = pasajData.buscarPasajeroDNI(dni);

            if(pasajActual != null){
                jtNombre.setText(pasajActual.getNombre());
                jtApellido.setText(pasajActual.getApellido());
                jtCorreo.setText(pasajActual.getCorreo());
                jtTel.setText(String.valueOf(pasajActual.getTel()));
                jbEliminar.setEnabled(true);
                jbBuscar.setEnabled(true);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Dni invalido");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDNIKeyReleased
        dniInvalido.setVisible(false);
    }//GEN-LAST:event_jtDNIKeyReleased

    private void jtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyReleased
        nombreInvalido.setVisible(false);
    }//GEN-LAST:event_jtNombreKeyReleased

    private void jtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoKeyReleased
        apellidoInvalido.setVisible(false);
    }//GEN-LAST:event_jtApellidoKeyReleased

    private void jtTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelKeyReleased
        telefonoInvalido.setVisible(false);
    }//GEN-LAST:event_jtTelKeyReleased

    private void jtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCorreoKeyReleased
        correoInvalido.setVisible(false);
    }//GEN-LAST:event_jtCorreoKeyReleased
    
     private void limpiarCampos(){
        jtNombre.setText("");
        jtApellido.setText("");
        jtDNI.setText("");
        jtCorreo.setText("");
        jtTel.setText("");
        nombreInvalido.setVisible(false);
        apellidoInvalido.setVisible(false);
        dniInvalido.setVisible(false);
        correoInvalido.setVisible(false);
        telefonoInvalido.setVisible(false);
    }
    
    private boolean validarEntero(String nro){
        Pattern patron=Pattern.compile("^[0-9]+$");
        Matcher match=patron.matcher(nro);
        return match.matches();
    }
    
    private boolean validarTexto(String string){
        Pattern patron = Pattern.compile("^[a-zA-ZáéíóúÁÉÍÓÚ]+$");
        Matcher match=patron.matcher(string);
        return match.matches();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoInvalido;
    private javax.swing.JLabel correoInvalido;
    private javax.swing.JLabel dniInvalido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtDNI;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTel;
    private javax.swing.JLabel nombreInvalido;
    private javax.swing.JLabel telefonoInvalido;
    // End of variables declaration//GEN-END:variables
}
