/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author pablo
 */
public class Gestion extends javax.swing.JPanel {
    GestionPasajeros gestionPasajeros = new GestionPasajeros();
    GestionColectivos gestionColectivos = new GestionColectivos();
    GestionRutaHorario gestionRutaHorario = new GestionRutaHorario();
    GestionColectivoRuta gestionColectivoRuta = new GestionColectivoRuta();
    boolean gestionesCreadas;
    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
        gestionEscritorio.addTab("Pasajeros", gestionPasajeros);
        gestionEscritorio.addTab("Colectivos", gestionColectivos);
        gestionEscritorio.addTab("Ruta y Horario", gestionRutaHorario);
        gestionEscritorio.addTab("Asignar colectivo a ruta", gestionColectivoRuta);
        gestionesCreadas = true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestionEscritorio = new javax.swing.JTabbedPane();

        gestionEscritorio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gestionEscritorioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gestionEscritorioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gestionEscritorioStateChanged
        if (gestionesCreadas) {
            if (gestionEscritorio.getSelectedIndex() == 3) { 
                gestionColectivoRuta.refrescarComboBox();
            } 
        }  
    }//GEN-LAST:event_gestionEscritorioStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane gestionEscritorio;
    // End of variables declaration//GEN-END:variables
}
