/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author pablo
 */
public class Gestion extends javax.swing.JPanel {
    GestionPasajeros gestionPasajeros = new GestionPasajeros();
    GestionColectivos gestionColectivos = new GestionColectivos();
    GestionRutaHorario gestionRutaHorario = new GestionRutaHorario();
    GestionPasaje gestionPasaje = new GestionPasaje();
    
    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
        gestionEscritorio.addTab("Pasajeros", gestionPasajeros);
        gestionEscritorio.addTab("Colectivos", gestionColectivos);
        gestionEscritorio.addTab("RutaHorario", gestionRutaHorario);
        gestionEscritorio.addTab("Pasajes",gestionPasaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestionEscritorio = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane gestionEscritorio;
    // End of variables declaration//GEN-END:variables
}
