/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;
import entidades.Pasajero;
import accesodatos.PasajerosData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pablo
 */
public class InfoPasajeros extends javax.swing.JPanel {
    private List<Pasajero> listaPasajeros;
    private List<Pasajero> listaNombre;
    private List<Pasajero> listaApellido;
    private PasajerosData pasajData;
    
    private DefaultTableModel modelo;

    /**
     * Creates new form infoPasajeros
     */
    public InfoPasajeros() {
        initComponents();
        pasajData = new PasajerosData();
        this.modelo = (DefaultTableModel) jtPasajeros.getModel();
        jrbPasajeros.setSelected(false);
        jrbNombre.setSelected(false);
        jrbApellido.setSelected(false);
        jrbPasajeros.setSelected(true);
        if(jrbPasajeros.isSelected()){
            listaPasajeros = pasajData.listarPasajeros();
            for(Pasajero p:listaPasajeros){
                modelo.addRow(new Object[]{p.getDni(),p.getNombre(),p.getApellido(),p.getTel()});
            }
        }
    }
    
    
    private void cargaNombres(){
        removerFilaTabla();
        String nombre = jtBuscar.getText().toLowerCase();
        listaNombre = pasajData.listarPorNombre(nombre);
        
        for(Pasajero pas: listaNombre){
            if(pas.getNombre().toLowerCase().equals(nombre)){
                modelo.addRow(new Object[]{pas.getDni(),pas.getNombre(),pas.getApellido(),pas.getTel()});
            }
        }
    }
    
    private void cargaApellidos(){
        removerFilaTabla();
        String apellido = jtBuscar.getText().toLowerCase();
        listaApellido = pasajData.listarPorApellido(apellido);
        
        for(Pasajero pas: listaApellido){
            if(pas.getApellido().toLowerCase().equals(apellido)){
                modelo.addRow(new Object[]{pas.getDni(),pas.getNombre(),pas.getApellido(),pas.getTel()});
            }
        }
    }
    
    private void removerFilaTabla(){
        int indice = modelo.getRowCount() -1;
        
        for(int i = indice; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtBuscar = new javax.swing.JTextField();
        jrbPasajeros = new javax.swing.JRadioButton();
        jrbNombre = new javax.swing.JRadioButton();
        jrbApellido = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPasajeros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });
        jtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBuscarKeyReleased(evt);
            }
        });
        add(jtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 137, 222, -1));

        jrbPasajeros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jrbPasajeros.setText("Pasajeros");
        jrbPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPasajerosActionPerformed(evt);
            }
        });
        add(jrbPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 139, -1, -1));

        jrbNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jrbNombre.setText("Nombre");
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });
        add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 139, -1, -1));

        jrbApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jrbApellido.setText("Apellido");
        jrbApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbApellidoActionPerformed(evt);
            }
        });
        add(jrbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 139, -1, -1));

        jtPasajeros.setBackground(new java.awt.Color(123, 166, 192));
        jtPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(jtPasajeros);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 175, 543, 243));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel2.setText("Buscar Pasajero:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 107, 148, -1));

        jLabel3.setFont(new java.awt.Font("Source Serif Pro Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Gestion Pasajeros");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPasajerosActionPerformed
        // TODO add your handling code here:
        listaPasajeros = pasajData.listarPasajeros();
        removerFilaTabla();
        jrbNombre.setSelected(false);
        jrbApellido.setSelected(false);
        for(Pasajero pas: listaPasajeros){
             modelo.addRow(new Object[]{pas.getDni(),pas.getNombre(),pas.getApellido(),pas.getTel()});
        }   
    }//GEN-LAST:event_jrbPasajerosActionPerformed

    private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
        // TODO add your handling code here:
        removerFilaTabla();
        jrbPasajeros.setSelected(false);
        jrbApellido.setSelected(false);
        cargaNombres();
        
        
    }//GEN-LAST:event_jrbNombreActionPerformed

    private void jrbApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbApellidoActionPerformed
        // TODO add your handling code here:
        removerFilaTabla();
        jrbPasajeros.setSelected(false);
        jrbNombre.setSelected(false);
        cargaApellidos();
    }//GEN-LAST:event_jrbApellidoActionPerformed

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscarActionPerformed

    private void jtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyReleased
        if (jrbNombre.isSelected()) {
            cargaNombres();
        }
        if (jrbApellido.isSelected()) {
            cargaApellidos();
        }
    }//GEN-LAST:event_jtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbApellido;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbPasajeros;
    private javax.swing.JTextField jtBuscar;
    private javax.swing.JTable jtPasajeros;
    // End of variables declaration//GEN-END:variables
}
