/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author pablo
 */
public class Listas extends javax.swing.JPanel {
    InfoRutaHorario rutaHorario = new InfoRutaHorario();
    InfoPasajes pasajes = new InfoPasajes();
    InfoPasajeros pasajeros = new InfoPasajeros();
    /**
     * Creates new form Listas
     */
    public Listas() {
        initComponents();
        infoEscritorio.addTab("Ruta y Horarios", rutaHorario);
        infoEscritorio.addTab("Pasajeros", pasajeros);
        infoEscritorio.addTab("Pasajes", pasajes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoEscritorio = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane infoEscritorio;
    // End of variables declaration//GEN-END:variables
}
