/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author pablo
 */
public class menuVistas extends javax.swing.JFrame {
    Inicio inicio = new Inicio();
    Gestion gestiones = new Gestion();
    /**
     * Creates new form menuVistas
     */
    public menuVistas() {
        initComponents();
        this.setLocationRelativeTo(null);
        escritorio.addTab("inicio",inicio);
        escritorio.addTab("geation", gestiones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbInformacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbInicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbGestiones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        escritorio = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(908, 588));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COLECTIVOS SL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jbInformacion.setBackground(new java.awt.Color(51, 102, 255));
        jbInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbInformacionMouseReleased(evt);
            }
        });
        jbInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ver informacion");
        jLabel2.setPreferredSize(new java.awt.Dimension(39, 19));
        jbInformacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, -1));

        jPanel1.add(jbInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 45));

        jbInicio.setBackground(new java.awt.Color(51, 102, 255));
        jbInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbInicioMouseReleased(evt);
            }
        });
        jbInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inicio");
        jLabel5.setPreferredSize(new java.awt.Dimension(39, 19));
        jbInicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(jbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, 200, 45));

        jbGestiones.setBackground(new java.awt.Color(51, 102, 255));
        jbGestiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbGestionesMouseReleased(evt);
            }
        });
        jbGestiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gestiones");
        jLabel6.setPreferredSize(new java.awt.Dimension(39, 19));
        jbGestiones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        jPanel1.add(jbGestiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 590));
        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -30, 730, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInicioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInicioMouseReleased
        escritorio.setSelectedIndex(0);
    }//GEN-LAST:event_jbInicioMouseReleased

    private void jbGestionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGestionesMouseReleased
        escritorio.setSelectedIndex(1);
    }//GEN-LAST:event_jbGestionesMouseReleased

    private void jbInformacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInformacionMouseReleased
        escritorio.setSelectedIndex(2);
    }//GEN-LAST:event_jbInformacionMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuVistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jbGestiones;
    private javax.swing.JPanel jbInformacion;
    private javax.swing.JPanel jbInicio;
    // End of variables declaration//GEN-END:variables
}
