/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import java.awt.*;

/**
 *
 * @author pablo
 */
public class menuVistas extends javax.swing.JFrame {
    Inicio inicio = new Inicio();
    Gestion gestiones = new Gestion();
    GestionPasaje ventaPasaje = new GestionPasaje();
    Listas listas = new Listas();
    boolean pestañasCreadas;
    /**
     * Creates new form menuVistas
     */
    public menuVistas() {
        initComponents();
        this.setLocationRelativeTo(null);
        escritorio.addTab("inicio",inicio);
        escritorio.addTab("gestion", gestiones);
        escritorio.addTab("ventaPasaje", ventaPasaje);
        escritorio.addTab("info",listas);
        pestañasCreadas = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbInformacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbInicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbVentaPasajes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbGestiones = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        escritorio = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(908, 588));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(0, 0, 204));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COLECTIVOS SL");
        jpMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jbInformacion.setBackground(new java.awt.Color(0, 51, 204));
        jbInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbInformacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbInformacionMouseReleased(evt);
            }
        });
        jbInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ver informacion");
        jLabel2.setPreferredSize(new java.awt.Dimension(39, 19));
        jbInformacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, -1));

        jpMenu.add(jbInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 45));

        jbInicio.setBackground(new java.awt.Color(0, 51, 204));
        jbInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbInicioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbInicioMouseReleased(evt);
            }
        });
        jbInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inicio");
        jLabel5.setPreferredSize(new java.awt.Dimension(39, 19));
        jbInicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, -1));

        jpMenu.add(jbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, 200, 45));

        jbVentaPasajes.setBackground(new java.awt.Color(0, 51, 204));
        jbVentaPasajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbVentaPasajesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbVentaPasajesMouseReleased(evt);
            }
        });
        jbVentaPasajes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Venta pasajes");
        jLabel6.setPreferredSize(new java.awt.Dimension(39, 19));
        jbVentaPasajes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jpMenu.add(jbVentaPasajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 45));

        jbSalir.setText("X");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jpMenu.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jbGestiones.setBackground(new java.awt.Color(0, 51, 204));
        jbGestiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbGestionesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbGestionesMouseReleased(evt);
            }
        });
        jbGestiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gestiones");
        jLabel7.setPreferredSize(new java.awt.Dimension(39, 19));
        jbGestiones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        jpMenu.add(jbGestiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 45));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 590));

        escritorio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                escritorioStateChanged(evt);
            }
        });
        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -30, 730, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInicioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInicioMouseReleased
        escritorio.setSelectedIndex(0);
        jbInicio.setBackground(new Color(0,51,204));
    }//GEN-LAST:event_jbInicioMouseReleased

    private void jbVentaPasajesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVentaPasajesMouseReleased
        escritorio.setSelectedIndex(2);
        jbVentaPasajes.setBackground(new Color(0,51,204));
    }//GEN-LAST:event_jbVentaPasajesMouseReleased

    private void jbInformacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInformacionMouseReleased
        escritorio.setSelectedIndex(3);
        jbInformacion.setBackground(new Color(0,51,204));
    }//GEN-LAST:event_jbInformacionMouseReleased

    private void jbInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInicioMousePressed
        jbInicio.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_jbInicioMousePressed

    private void jbVentaPasajesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVentaPasajesMousePressed
        jbVentaPasajes.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_jbVentaPasajesMousePressed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGestionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGestionesMousePressed
        jbGestiones.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_jbGestionesMousePressed

    private void jbGestionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGestionesMouseReleased
       jbGestiones.setBackground(new Color(0,51,204));
       escritorio.setSelectedIndex(1);
    }//GEN-LAST:event_jbGestionesMouseReleased

    private void jbInformacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbInformacionMousePressed
        jbInformacion.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_jbInformacionMousePressed

    private void escritorioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_escritorioStateChanged
        
    }//GEN-LAST:event_escritorioStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuVistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jbGestiones;
    private javax.swing.JPanel jbInformacion;
    private javax.swing.JPanel jbInicio;
    private javax.swing.JButton jbSalir;
    private javax.swing.JPanel jbVentaPasajes;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
