/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import entidades.Pasaje;

/**
 *
 * @author pablo
 */
public class ReciboPago extends javax.swing.JPanel {
    Pasaje pasaje;
    /**
     * Creates new form ReciboPago
     * @param pasaje
     */
    public ReciboPago(Pasaje pasaje) {
        initComponents();
        this.pasaje = pasaje;
        jlRutaRec.setText(pasaje.getRuta().toString());
        jlColectivoRec.setText(pasaje.getColectivo().toString());
        jlFechaRec.setText(pasaje.getFechaViaje().toString());
        jlHorarioRec.setText(pasaje.getHoraViaje().toString());
        jlPasajeroRec.setText(pasaje.getPasajero().toString());
        jlAsientoRec.setText(pasaje.getAsiento()+"");
        jlPrecioRec.setText(pasaje.getPrecio()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlPrecioRec = new javax.swing.JLabel();
        jlRutaRec = new javax.swing.JLabel();
        jlColectivoRec = new javax.swing.JLabel();
        jlHorarioRec = new javax.swing.JLabel();
        jlFechaRec = new javax.swing.JLabel();
        jlPasajeroRec = new javax.swing.JLabel();
        jlAsientoRec = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ruta:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 37, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Colectivo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Duracion:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 52, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pasajero:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Asiento:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Precio:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, -1));

        jlPrecioRec.setForeground(new java.awt.Color(0, 0, 0));
        jlPrecioRec.setText("texto");
        add(jlPrecioRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 320, -1));

        jlRutaRec.setForeground(new java.awt.Color(0, 0, 0));
        jlRutaRec.setText("texto");
        add(jlRutaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 320, -1));

        jlColectivoRec.setForeground(new java.awt.Color(0, 0, 0));
        jlColectivoRec.setText("texto");
        add(jlColectivoRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 320, -1));

        jlHorarioRec.setForeground(new java.awt.Color(0, 0, 0));
        jlHorarioRec.setText("texto");
        add(jlHorarioRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 320, -1));

        jlFechaRec.setForeground(new java.awt.Color(0, 0, 0));
        jlFechaRec.setText("texto");
        add(jlFechaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 320, -1));

        jlPasajeroRec.setForeground(new java.awt.Color(0, 0, 0));
        jlPasajeroRec.setText("texto");
        add(jlPasajeroRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 320, -1));

        jlAsientoRec.setForeground(new java.awt.Color(0, 0, 0));
        jlAsientoRec.setText("texto");
        add(jlAsientoRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 320, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlAsientoRec;
    private javax.swing.JLabel jlColectivoRec;
    private javax.swing.JLabel jlFechaRec;
    private javax.swing.JLabel jlHorarioRec;
    private javax.swing.JLabel jlPasajeroRec;
    private javax.swing.JLabel jlPrecioRec;
    private javax.swing.JLabel jlRutaRec;
    // End of variables declaration//GEN-END:variables
}
